### PR TITLE
fixes #294

### LINKED ISSUE #294: error with extends local config having sublevels of node_modules folders
In v5.2.0 i have one case where i'm still getting the error using local plugin extends.

I'm working in a browserify project where i have the next folder structure:
```
node_modules/
src/
    components/
    styles/
    node_modules/
    index.js
.eslintrc
gulpfile.js
package.json
```
If i check the gulpfile.js with atom-eslint everthing works great. But if i check the src/index.js atom-eslint is trying to find the eslint config plugin in src/node_modules/ instead of the root node_modules, throwing the error: Cannot find module 'eslint-config-airbnb'

Note: in v4.0.0 is working fine.

### PR DESCRIPTION
**Pull request by aruberto**
The 6.0.0 release seems to have broken #294.

This pull request is just re-applying @grabbou original fix from #396 that searches for node_modules/eslint instead of node_modules.

[Review on Reviewable](https://reviewable.io/reviews/atomlinter/linter-eslint/409)

### CODE REVIEW

**Comment by steelbrain** [comment]
It would be nice to have a test for this so we don't accidentally break this on a future version

Also run `npm run compile` to compile the file

**Comment by aruberto** [comment]
@steelbrain  Sounds good, let me try and add test for it.

**Comment by steelbrain** [comment]
@aruberto Looks good! Waiting on CI

**Comment by steelbrain** [comment]
@aruberto Thanks :clap:

**Comment by Arcanemagus** [comment]
Published in v6.1.0. :tada:

**Pull request merged**
