### PR TITLE
Support for multiple rules dirs

### PR DESCRIPTION
**Pull request by christopherstott**
I added support for passing in multiple rules dirs to eslint.

Added a new array config property eslintRulesDirs (left eslintRulesDir as is to not break existing functionality).

[Review on Reviewable](https://reviewable.io/reviews/atomlinter/linter-eslint/342)

### CODE REVIEW

**Comment by steelbrain** [comment]
Instead of having two configs `eslintRulesDirs` and `eslintRulesDir`, how about we modify `eslintRulesDir` to accept an array and keep that key for backward compatibility and add a custom title with `Dirs`?

**Comment by christopherstott** [comment]
That's what I was originally hoping to do.

Is there a way to do that and pass the type validation? Currently 'eslintRulesDir' must be a 'string'.

I'm not sure what you mean by "add a custom title with Dirs" ?

Thanks

**Comment by steelbrain** [comment]
```js
    eslintRulesDir: {
      title: 'ESLint Rules Dirs',
      description: 'Specify comma separated directories for ESLint to load rules from',
      type: 'array',
      default: []
    }
```
The key remainds same `eslintRulesDir` for backward compatibility and now we accept an array

**Comment by Arcanemagus** [comment]
What about existing configurations @steelbrain?

**Comment by steelbrain** [comment]
@Arcanemagus If we do what I suggested, it should be backward compatible

**Comment by Arcanemagus** [comment]
So it would read in any existing settings without issue?

**Comment by steelbrain** [comment]
@Arcanemagus True

**Comment by Arcanemagus** [comment]
@christopherstott Have you had a chance to update your PR yet?

**Comment by Arcanemagus** [comment]
@christopherstott Can you rebase this PR and address @steelbrain's comments?

**Comment by Arcanemagus** [comment]
Marking this as closed due to a lack of response.

**Pull request closed without merging**
