### PR TITLE
Support .eslintignore

### LINKED ISSUE #279: linter-eslint doesn't respect .eslintignore
`linter-eslint` version `5.1.0`
`atom` version `1.2.0`
`OS X` Yosemite

`linter-eslint` not ignoring folders in `.eslintignore`

when i try `eslint` from CLI:
```
/···/···.js
  0:0  warning  File ignored because of your .eslintignore file. Use --no-ignore to override
```

the `eslint` error for the file that should be ignored is "unused var"

### PR DESCRIPTION
**Pull request by steelbrain**
Fixes #279

[Review on Reviewable](https://reviewable.io/reviews/atomlinter/linter-eslint/287)

### CODE REVIEW

**Comment by ismay** [comment]
Has this fix been published? Because I'm still getting the bugs that were fixed in this PR with atom-eslint v5.2.0

**Comment by micky2be** [comment]
Still have the problem here.

**Comment by aMarCruz** [comment]
Also in v5.2.6 - Atom 1.3.2 + Linux Mint 17.2

**Comment by IanVS** [comment]
@ismay, @micky2be, @aMarCruz, would one of you please submit an issue with the details of the problems you are having and steps to reproduce?

**Comment by micky2be** [comment]
Seems to work fine for me now. 
I believe I made a mistake on the syntax of how to ignore all the web_modules folders. 
Thanks anyway

**Comment by aMarCruz** [comment]
@IanVS , I restarted Atom and everything is ok, I guess it was the cache. Thanks!

**Pull request merged**
