### PR TITLE
dependencies fix

### PR DESCRIPTION
**Pull request by willin**
Err.1:

```
Error: Cannot read config file: /Users/willin/.atom/packages/linter-eslint/node_modules/eslint-config-airbnb/base.js Error: ENOENT: no such file or directory, open '/Users/willin/.atom/packages/linter-eslint/node_modules/eslint-config-airbnb/base.js' Referenced from: /Users/willin/Documents/w2fs/auto-deployer/.eslintrc.json
Error: Cannot read config file: /Users/willin/.atom/packages/linter-eslint/node_modules/eslint-config-airbnb/base.js
Error: ENOENT: no such file or directory, open '/Users/willin/.atom/packages/linter-eslint/node_modules/eslint-config-airbnb/base.js'
Referenced from: /Users/willin/Documents/w2fs/auto-deployer/.eslintrc.json
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.Module._extensions..js (module.js:451:20)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

Err.2:

```
Error: Cannot read config file: /Users/willin/.atom/packages/linter-eslint/node_modules/eslint-config-airbnb/base.js Error: ENOENT: no such file or directory, open '/Users/willin/.atom/packages/linter-eslint/node_modules/eslint-config-airbnb/base.js' Referenced from: /Users/willin/Documents/w2fs/auto-deployer/.eslintrc.json
Error: Cannot read config file: /Users/willin/.atom/packages/linter-eslint/node_modules/eslint-config-airbnb/base.js
Error: ENOENT: no such file or directory, open '/Users/willin/.atom/packages/linter-eslint/node_modules/eslint-config-airbnb/base.js'
Referenced from: /Users/willin/Documents/w2fs/auto-deployer/.eslintrc.json
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.Module._extensions..js (module.js:451:20)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

### CODE REVIEW

**Comment by IanVS** [comment]
Sorry, but this is not the right way to solve those errors.  Those packages are dev dependencies for this project and are not necessary for it to work correctly for end users.  The reason you are seeing the errors is that you are also trying to use the airbnb config, but you haven't installed it in your project.  You also seem to have not installed eslint either, so linter-eslint is falling back to the version which is packaged with it.

So, to solve your problems, you should do this from your project directory:

```shell
npm install --save-dev eslint eslint-config-airbnb
```

And since you've also moved babel-eslint and eslint-plugin-react, I assume you're also using those, so you should:

```shell
npm install --save-dev eslint-plugin-react babel-eslint
```

Then restart Atom, and the errors should disappear.  If they don't, let us know and we'll try to troubleshoot further.

**Comment by willin** [comment]
no use.

**Comment by Arcanemagus** [comment]
What is "no use"?

**Comment by willin** [comment]
try it yourself...

**Comment by Arcanemagus** [comment]
I use the linter every day, it works perfectly fine. Did you read @IanVS's comment? It details the most likely problem you are facing, as well as how to solve it.

**Pull request closed without merging**
