### PR TITLE
restore cursor position after fix command

### PR DESCRIPTION
**Pull request by yacut**
The cursor at the moment jumps to the beginning of the file after the fix command. It infuriates me :)

### CODE REVIEW

**Comment by IanVS** [comment]
Thanks for the contribution, @yacut!

**Comment by yacut** [comment]
@IanVS, could you please publish the changes?

**Comment by IanVS** [comment]
Actually, I've been using `master` lately which includes this change, and it does not seem to have fixed the underlying problem, unfortunately.  We may need to revert it back out, since it does not have the intended effect.  Before we do that, it would be great if I could get confirmation from someone else that this does not solve the cursor problem.  

To do that, uninstall `linter-eslint` from atom, clone this repo, then `apm link` from inside the repo.  Then use it for a while and see if the cursor still jumps to the start of the file occationally when fixing on save.

**Comment by yacut** [comment]
I already installed it from the master and it's works works for me: https://giphy.com/gifs/linter-eslint-3o7bubhh3ZUgFe41qg/fullscreen
The cursor stays in the current position after the autofix.

**Comment by IanVS** [comment]
It usually works for me too, the cursor resetting is intermittent.  Can you leave it on for several days and report back whether it _never_ resets.  It happens once or twice a day for me, usually.

**Pull request merged**
