### PR TITLE
Use `eslint-rule-documentation` to get rule documentation links

### PR DESCRIPTION
**Pull request by jfmengels**
Use `eslint-rule-documentation` to get rule documentation links, as proposed in #590.

This was pretty straightforward, but this part didn't have tests and I'm not sure how to test this in Atom. Can I ask you for guidance in order to test this properly? (Unless you find this too straightforward and you can test it easily)

### CODE REVIEW

**Comment by Arcanemagus** [comment]
Just triggering a rule violation in a file that _should_ return a linkable rule should be sufficient... I thought this was already happening but apparently not 😕.

Looks like I noticed it wasn't working a while back (#473), but never looked into it.

`linter-eslint.showRuleIdInMessage` should be the config key determining this, but the default value is true so I'm not sure how the specs are running with it as `false`...

**Comment by IanVS** [comment]
image

👏 I love these kinds of PRs.

**Comment by Arcanemagus** [comment]
@jfmengels As soon as the `npm run compile` changes are in here this can get merged!

**Comment by jfmengels** [comment]
Ah cool. I just left on holidays, and didn't bring my laptop with me. Feel free to take the work done here and add `npm run compile`, or wait a week and I'll do it :)

**Comment by jfmengels** [comment]
I've rebased with master, and added the compilation changes in there. Sorry for the delay on this

**Comment by Arcanemagus** [comment]
No worries, thanks for taking this on!

**Comment by jfmengels** [comment]
Yay! Thanks!
By the way, feel free to add people as maintainers of `eslint-rule-documentation` as you see fit.

**Pull request merged**
