### PR TITLE
Add images for wiki

### PR DESCRIPTION
**Pull request by IanVS**
These are images which will be used on the page explaining how to contribute rule doc links.

### CODE REVIEW

**Comment by IanVS** [comment]
Hm, the files seem to have been corrupted somehow.

**Comment by IanVS** [comment]
Ah, had to tell git to treat .png files as binary.

**Comment by Arcanemagus** [comment]
Yea it _should_ auto-detect binary files and not mess with them according to the documentation... but it's pretty bad about that :disappointed:.

**Comment by Arcanemagus** [comment]
Not sure what these are foor yet, but LGTM :stuck_out_tongue:.

**Comment by IanVS** [comment]
I put them in https://github.com/AtomLinter/linter-eslint/wiki/Linking-to-Rule-Documentation (a work in progress).

**Pull request merged**
