### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by nmote**
- Add missing `waitsForPromise` wrappers -- without these, test failures can get misattributed or ignored altogether
- Set the `disableEslintIgnore` setting to `true` for all tests, except the one that actually tests it. Otherwise the "finds nothing wrong" tests are useless. This can be demonstrated by reverting my changes to `good.js` -- it actually did contain a lint error :stuck_out_tongue:

[Review on Reviewable](https://reviewable.io/reviews/atomlinter/linter-eslint/413)

### CODE REVIEW

**Comment by nmote** [comment]
I'm not really sure how to stack another pull request on top of this one, so I will just wait until this one is closed to submit my autofix one. Also, this will hopefully get updated properly when the document-build branch gets merged. We will find out.

**Comment by Arcanemagus** [comment]
Looks like you need to run `npm install` to update your config packages.

**Comment by Arcanemagus** [comment]
And when it was originally written `good.js` didn't contain any errors, the styles have changed since then though and it just wasn't exposed yet :stuck_out_tongue:.

**Comment by nmote** [comment]
I did run `npm install`, and `apm test` passed on my machine. The problem is that I guess I rebased past some lint rule changes.

**Comment by Arcanemagus** [comment]
Oh! You did this PR off the `document-build` branch, not master!

**Comment by nmote** [comment]
Yeah, I wanted to pick up and try out the scripts for transpilation.

**Comment by Arcanemagus** [comment]
Looks like the changes are good, but I think you'll need to resubmit against `master`.

**Comment by nmote** [comment]
Ah ok. I'm not super familiar with GitHub so I was hoping that it would be marked as dependent on that branch somehow and then update properly when it was merged.

**Comment by nmote** [comment]
Revived in #414. Sorry about that.

**Comment by Arcanemagus** [comment]
No problem, sorry for the confusion :wink:.

**Pull request closed without merging**
