### PR TITLE
Interpolate env var in conf path

### LINKED ISSUE #291: EsLint of standalone JS not working after v3.1.1
I open JS files in isolation sometimes, when there is no related project or .eslintrc file.

Under these conditions under 3.1.1 it does run EsLint with the default rules, which is nice for catching some issues when scanning code.

This hasn't been working for a while, despite the following in my config.cson.
```javascript
  "linter-eslint":
    disableWhenNoEslintrcFileInPath: false
```
Downgrading to 3.1.1 gives the desired behavior, any version after does not work.

I was thinking someone must have reported this, so have been manually downgrading to 3.1.1 on every update for a few weeks :scream:

### PR DESCRIPTION
**Pull request by SpainTrain**
* :new: Interpolate environment variables in the provided path for the eslint config file

Closes #291

[Review on Reviewable](https://reviewable.io/reviews/atomlinter/linter-eslint/297)

### CODE REVIEW

**Comment by steelbrain** [comment]
While what you did looks nice but I wouldn't trust a module who is not popular and we don't even know it's author, what if he doesn't follow semver and breaks the API?

I would highly recommend we pin the version of it or find an alternative package that is more trust worthy

**Comment by JohnMurga** [comment]
The entire code for the module appears to be 15 lines :-)
https://github.com/LinusU/node-resolve-env/blob/master/index.js

**Comment by SpainTrain** [comment]
I really doubt that will be an issue given that the author has many packages (https://www.npmjs.com/~linusu) and is a member on @expressjs (https://github.com/LinusU)

@LinusU, can you comment on following semver in your projects?

**Comment by SpainTrain** [comment]
RE: LOC - https://github.com/sindresorhus/ama/issues/10#issuecomment-117766328

**Comment by JohnMurga** [comment]
@SpainTrain ... Agreed ... I was thinking more about risk in relation to complexity

**Comment by SpainTrain** [comment]
oh gotcha! :+1:

**Comment by LinusU** [comment]
I promise to follow semver, which I do with all of my modules :)

I also fullheartedly agree with https://github.com/sindresorhus/ama/issues/10#issuecomment-117766328 and I'm usually very fast at responding to bug reports.

**Comment by SpainTrain** [comment]
Thanks for responding!

strangers-npm


@steelbrain are we good to merge?

**Comment by LinusU** [comment]
Awesome :+1:

**Comment by steelbrain** [comment]
@LinusU Thank you for a nice package! :+1:

**Comment by Arcanemagus** [comment]
Published in v5.2.1.

**Comment by JohnMurga** [comment]
Thanks all :+1: 
However, has to extend this to the "eslintrcPath" with this https://github.com/AtomLinter/linter-eslint/pull/305 tiny patch.
Now it works for me in combination with setting the the disableWhenNoEslintrcFileInPath config.

**Pull request merged**
