### PR TITLE
Convert null to empty string inside path.dirname()

### LINKED ISSUE #580: Path type check fails with Node 6
Node 6 (which is included in Electron 1.1.0) became more strict about the input type of `path` methods (https://github.com/nodejs/node/commit/08085c49b6e49ecfffd638c6cd46f4de639ae4f4).

As a result, the following error pops up when running Atom with the latest Electron and linter-eslint:

```
TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at Object.getESLintInstance (/home/nicola/.atom/packages/linter-eslint/lib/worker-helpers.js:87:35)
    at /home/nicola/.atom/packages/linter-eslint/lib/worker.js:59:24
    at Emitter.emit (/home/nicola/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-event-kit/lib/emitter.js:70:19)
    at /home/nicola/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-communication/lib/main.js:22:23
    at /home/nicola/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-communication/lib/main.js:21:24
    at Emitter.emit (/home/nicola/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-event-kit/lib/emitter.js:68:19)
    at Communication.parseMessage (/home/nicola/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-communication/lib/main.js:63:18)
    at process.ProcessCommunication.messageCallback (/home/nicola/.atom/packages/linter-eslint/node_modules/process-communication/lib/communication.js:35:27)
```

### PR DESCRIPTION
**Pull request by tensor5**
Fixes #580.

### CODE REVIEW

**Comment by IanVS** [comment]
@tensor5 sorry, but it looks like there is a merge conflict.  If you could rebase this, I'll be happy to merge since it's obviously causing some people some pain.

**Comment by tensor5** [comment]
@IanVS, please try now.

**Comment by Arcanemagus** [comment]
No merge conflicts locally, and this fixes an issue with the upcoming Electron upgrade in Atom so I'm forcing a merge, thanks!

**Comment by tensor5** [comment]
Thanks!

**Pull request merged**
