### PR TITLE
Lint javascript inside HTML file

### PR DESCRIPTION
**Pull request by mehwww**
#194 Use [executeOnText](http://eslint.org/docs/developer-guide/nodejs-api.html#executeontext) instead of [linter](http://eslint.org/docs/developer-guide/nodejs-api.html#linter) because `linter` does not support [plugin](https://github.com/BenoitZugmeyer/eslint-plugin-html)

### CODE REVIEW

**Comment by mehwww** [comment]
Maybe we should add a option for this feature?

**Comment by yuche** [comment]
So helpful.Thanks.
@mehwww

**Comment by ikeagold** [comment]
:+1: @iam4x pls, because its a last reason why many people still using jshint+jscs

**Comment by Arcanemagus** [comment]
Have you done any testing on this? I would imagine that `eslint` is expecting you to feed it some JavaScript to lint, but this PR is simply feeding it the entire contents of the file you are editing. How would it handle mixed HTML and JavaScript, much less more complex combinations?

**Comment by mehwww** [comment]
I personally use eslint to lint html files with [a eslint plugin](https://github.com/BenoitZugmeyer/eslint-plugin-html), so if you are planning to support this feature maybe you shall mention it in the document or setting things, or I guess there will be a lot of code do the spliting things

**Comment by ikeagold** [comment]
Is eslint on ST3 won't lint inline js too? or its only Atom have this issue's? and same issue in jshint(maybe linter-xo too) from @sindresorhus .
@mehwww thanx for eslint-html, but can't find it on (atom.io/packages](https://atom.io/packages/)

**Comment by ikeagold** [comment]
@mehwww maybe you rebase pull and make it on logic like [here](https://github.com/AtomLinter/linter-jshint/blob/master/lib/main.coffee#L25-L29) (from atom-jshint), this logic clean and looking ok) and working fine ;)

**Comment by mehwww** [comment]
@ikeagold It's an eslint plugin but not an atom package, you need install it via `npm install eslint-plugin-html` locally or globally, see [here](http://eslint.org/docs/user-guide/configuring#configuring-plugins)
And it's fair enough making it more logic, but i'd rather let the maintainer decide how to support this feature, by default or provide a configure option or somewhat else

**Comment by Arcanemagus** [comment]
@ikeagold The part of `linter-jshint` you linked has nothing to do with this beyond saying it can handle those scopes, the relevant part of that file is [here](https://github.com/AtomLinter/linter-jshint/blob/master/lib/main.coffee#L55) where it tells `jshint` to do the extraction for it.

I don't think requiring an `eslint` plugin is the way to go here since one of the large parts of this is that you can use a custom installation with no additional dependencies. If this is going to be supported the extraction would need to be done locally in this package in some manner.

**Comment by Arcanemagus** [comment]
@mehwww It would be great to see a PR (maybe this one? :stuck_out_tongue:) that properly supports that, but it's more involved than what you have here.

Unless of course I'm totally wrong, I am only basing this on the description of `executeOnText()` and haven't verified it doesn't already work myself after all, hence asking if you had tested this :wink:.

**Comment by mehwww** [comment]
@Arcanemagus I‘ve updated my PR, update the deps, drop support for old eslint and requrie the plugin locally and conditionally load it. It works well here and you may test this :wink:.

**Comment by ikeagold** [comment]
@mehwww thanks man, brilliant job :+1:

**Comment by iam4x** [comment]
@mehwww Going to test this :+1: 

Sorry for not being much present here. We raised 15M where I work, and now things are going at the office...

**Comment by iam4x** [comment]
:ship:

**Pull request merged**
