### PR TITLE
Support local gulp-eslint installations.

### PR DESCRIPTION
**Pull request by onlywei**
Addresses #202.

### CODE REVIEW

**Comment by IanVS** [comment]
Shouldn't the `eslint` within `gulp-eslint` already be found by `resolve.sync` as it is?

**Comment by onlywei** [comment]
@IanVS It does not seem to work that way.

**Comment by onlywei** [comment]
@IanVS For example, I cannot do `require('eslint')` directly in my local files, I can only do `require('gulp-eslint')`.

**Comment by IanVS** [comment]
Guess so, at least until everyone is using `npm 3.0.0`, wherein:

> Dependencies will now be installed maximally flat. Insofar as is possible, all of your dependencies, and their dependencies, and THEIR dependencies will be installed in your project's node_modules folder with no nesting. You'll only see modules nested underneath one another when two (or more) modules have conflicting dependencies.

**Comment by onlywei** [comment]
@IanVS I don't think we should wait for that to happen. AFAIK NPM 3.0.0 isn't even out yet.

**Comment by IanVS** [comment]
It's in [beta](https://github.com/npm/npm/releases/tag/v3.3.3) right now, but I wasn't suggesting to wait for it.  It still seems like there should be a better way to accomplish this, but I don't know what it would be.

**Comment by onlywei** [comment]
@iam4x do you have an opinion on this?

**Comment by steelbrain** [comment]
Fixed in another way by #258

**Comment by onlywei** [comment]
Installed v5.0.0. Tested. Works! Thanks!

**Comment by MatthewHerbst** [comment]
This doesn't seem to be working properly anymore.

```
Atom v1.7.3
Atom linter-eslint v7.2.2
Node v4.2.6
npm v2.14.12
```
Locally installed/package.json
```
gulp-eslint v2.0.0
eslint-plugin-react v5.0.1
```

When I open a file in Atom, I get an error that the `eslint-plugin-react` module can't be found. This error is resolved by locally installing `eslint`.

Or did I miss something?

**Comment by Arcanemagus** [comment]
@MatthewHerbst The discussion above is talking about taking advantage of a fluke in how `npm@^3` installs dependencies... if you want to have a guaranteed `eslint` available you should explicitly list it.

Supporting grabbing the sub-dependency of `gulp-eslint` in all possible situations isn't something that I feel should be supported in this package.

**Comment by MatthewHerbst** [comment]
@Arcanemagus ah alright. That's fine by me, I just thought the above meant finding sub-dependency grabbing should be supported.

It could be worth making a UI option where a user could specify a path to a specific install of `eslint`

**Pull request closed without merging**
