### PR TITLE
Fix: 'Fix on Save' should run only in valid file types

### PR DESCRIPTION
**Pull request by pvamshi**
We already have valid scopes listed as 

```js
this.scopes = ['source.js', 'source.jsx', 'source.js.jsx', 'source.babel', 'source.js-semantic']
```

I am using the same array and comparing if the file type belongs to one of them .
With this fix, it is not running in all file types. 
Please validate.

### CODE REVIEW

**Comment by IanVS** [comment]
It really seems like this should be more flexible, since we can't predict what file extensions everyone will use for javascript.  This is a good start to address the immediate bug, but I think a more flexible solution would be to lint (and fix) only `.js` files by default and provide an option for the user to configure others.

**Comment by pvamshi** [comment]
Probably that should be valid for general linting. So that would directly change `this.scopes` array and this fix is still valid even in that case . 
Is my understanding correct ?

**Comment by Arcanemagus** [comment]
This looks correct to me at least.

@IanVS I'm not sure what you are talking about here, this linter (and the changes in this PR) are based on the _scope_ as Atom sees it, not the extension on the file.

Or is there a limitation on `eslint`'s side that only pure JavaScript files can be fixed?

**Comment by pvamshi** [comment]
Can we please merge this if the fix looks fine ?

**Comment by IanVS** [comment]
Ah ok, I assumed the scope was determined by the extension.  Looks good to me then.

**Comment by Arcanemagus** [comment]
That's essentially true for JavaScript, as the only place where I know of that `source.js` is valid is a pure `.js` file, but it's however Atom determines the scope really, which is controlled by the language packages.

**Comment by Arcanemagus** [comment]
Published in v7.2.1. :tada:

**Pull request merged**
