### PR TITLE
Supress warnings about the current file being ignored by eslint

### PR DESCRIPTION
**Pull request by broberson**
Addresses AtomLinter/linter-eslint#669

### CODE REVIEW

**Comment by IanVS** [comment]
Thanks, while you're at it, could you also add

`'File ignored by default. Use "--ignore-pattern '!node_modules/*'" to override'`

and 

`'File ignored by default. Use "--ignore-pattern '!bower_components/*'" to override'`

?

That should cover all the permutations on the ESLint default ignore messages.

**Comment by broberson** [comment]
Happy to. Thanks Ian.

**Comment by broberson** [comment]
CircleCI doesn't like that eslint's warning message is over 100 characters, but splitting it into multiple strings to make a bot happy just felt wrong. I can do that though, if you're a stickler for green checkmarks.

**Comment by Arcanemagus** [comment]
@broberson The style checks are in there for a reason 😉.

Split the line up, run `npm run compile` again (it's currently out of date) and we'd love to merge this, thanks for putting this together!

**Comment by broberson** [comment]
There you go. Thanks :)

**Comment by IanVS** [comment]
Thanks @broberson!

**Pull request merged**
