### PR TITLE
Add support for globally installed eslint, engines and plugins

### PR DESCRIPTION
**Pull request by yamalight**
I'd added some code to get global npm node_modules folder and try to load eslint, engines and plugins from there. This addresses issue #35 in a better way (IMO) since there's no need to install same packages to every repo you code in. They can now just be installed globally and linter-eslint will fall back to them if no local ones found.

### CODE REVIEW

**Comment by yamalight** [comment]
@iam4x any feedback on this one?

**Comment by iam4x** [comment]
Can you rebase it on master? I didn't noticed your PR sorry mate.

**Comment by yamalight** [comment]
@iam4x ah, though that might be the case, should've ping you earlier :D 
will rebase and ping you once more!

**Comment by iam4x** [comment]
And would be great to have an option to enable / disable looking for global eslint version :+1:

**Comment by yamalight** [comment]
hm, still a merge conflict after rebase. might be easier to drop and re-fork at this point :|
will close this PR and do another one once it's done. also will add the option for enabling this.

**Pull request closed without merging**
